### ISSUE TITLE
Project imported to idea. But it doesn't work

### ISSUE THREAD

**Issue by guoxunbo** [kenta-shimizu/secs4java8#1]
Like this image. It's some file dont commit? like pom.xml?
![image](https://user-images.githubusercontent.com/14329149/90499119-b90bb280-e17b-11ea-94fe-78995076432c.png)

**Comment by guoxunbo** [comment]
Oh. I know it。。。It's Ok now. Thank you

**Comment by guoxunbo** [comment]
Oh. I had see the code? it's with jdk11?

**Comment by gt2ming** [comment]
> Oh. I know it。。。It's Ok now. Thank you

I encountered the same problem, how did you solve it?

**Comment by kenta-shimizu** [comment]
Hi,

I'm not using idea,
I don't know details,
but maybe,
import from 'src/main/java/', not from 'src/'.

**Comment by gt2ming** [comment]
> Hi,
> 
> I'm not using idea, I don't know details, but maybe, import from 'src/main/java/', not from 'src/'.

Thanks for the reply!
This is my first exposure to SECS/GEM
Is there any information I can read, or learn from?
Or how do I learn about it?
Looking forward to your answer!

**Comment by kenta-shimizu** [comment]
Information of SECS is not normally found.
SEMI is not open community.

SEMI sell standard document.
<https://www.semi.org/>

Buy and read standard document.
Or attend occasional seminar.

I recommend attending the seminar.
I also attend in the past.

**Comment by gt2ming** [comment]
Thank you for your reply.

And I hope I can ask you again in the future!
