### ISSUE TITLE
Hello, excuse me，do you have a document corresponding to the code, some places are not clear😂

### ISSUE THREAD

**Issue by Polarisaaa** [kenta-shimizu/secs4java8#10]
Recently, I am learning SECS knowledge, and I also read your code, but the comments are a little less, and I feel that I don’t understand many places. Excuse me, do you have a code document for reference, thank you very much!

**Comment by kenta-shimizu** [comment]
Hi,
I write comment mainly on interface. I don't write comment on code.
If you learn, I recommend that buy and read SEMI standard document, or attend the seminar.
best regards.

**Comment by Polarisaaa** [comment]
I see, thank you!
