### ISSUE TITLE
Clarify API scope

### ISSUE THREAD

**Issue by holgerbrandl** [kenta-shimizu/secs4java8#11]
Great work!

It's a bit unclear to me if the library allows only consuming SECS/GEM server or if it also could be used to serve a SECS/GEM endpoint. Could this be clarified in the documentation (maybe including an example)?

**Comment by kenta-shimizu** [comment]
Hi,
This library can be used for both.
In HSMS-SS(E37.1), It is expressed as active/passive.

"active" executes "AsynchronousSocketChannel#connect".
"active" is suitable for client/consumer.

"passive" executes "AsynchronousServerSocketChannel#bind".
"passive" is suitable for equipment/endpoint.

This can be set with "HsmsSsCommunicatorConfig#connectionMode".

Best regards.

**Comment by holgerbrandl** [comment]
Thank you so much for the clarification.
