### ISSUE TITLE
based on jdk9 Or later not based on jdk8

### ISSUE THREAD

**Issue by shyding** [kenta-shimizu/secs4java8#2]

**Comment by kenta-shimizu** [comment]
Hi,
Exclude 'module-info.java', if using jdk8, or if it interferes on compile.
I will append this discription to 'module-info.java' comment.
Thanks regards.

**Comment by kenta-shimizu** [comment]
I mistake.
I use 'Collectors#toUnmodifiableList'(from 10)
And use 'Collection#toArray​(IntFunction<T[]>)'(from 11)
Thanks regards.

**Comment by kenta-shimizu** [comment]
Bug fixed.

**Comment by shyding** [comment]
If you're inclined to keep the file module.java After all, manually Exclude
 this file is always one step more, which is very inconvenient for development

**Comment by kenta-shimizu** [comment]
This repository is Apache License 2.0.
Fork to your repository and rewrite.
I hope your development environment will be comfortable.
