### ISSUE TITLE
running example error

### ISSUE THREAD

**Issue by saberKafu** [kenta-shimizu/secs4java8#3]
>I use the host '127.0.0.1' and port '5000' to run the example，but an error was occured. 
"AbstractHsmsSsActiveCommunicator#open AsynchronousSocketChannel#connect failed"

**Comment by kenta-shimizu** [comment]
Hi,

If this error is occurred in 'example2/ExampleHsmsSsActive.java',
run 'example1/ExampleHsmsSsPassive.java' with example2, too.

example1 is passive equipment.
example2 is active host.

Active example try-connect repeatedly until 'SELECTED' with T5-timeout intervals.

I will append this 'how to use' to Example class comment.

This example2 is not linked from README.md, I am glad that you saw and ran example2.
Thanks regards.

**Comment by saberKafu** [comment]
Thanks, now I can run the example successfully.
