### ISSUE TITLE
Some questions about Example 5: ExampleHsmsGsActiveOne

### ISSUE THREAD

**Issue by btbtbtbjjzz** [kenta-shimizu/secs4java8#39]
Hello：
When I was running Example 5 ActiveOne, the Host established a TCP connection with the Passive system normally, but after sending S1F15, the TCP disconnected and the console encountered the error shown in the diagram. Would you like to tell me how this happened. In addition, what is the difference between ActiveOne and ActiveTwo?
![image](https://github.com/kenta-shimizu/secs4java8/assets/87190197/5faab223-5d8f-4e1d-8d99-56b4b7065dbf)

**Comment by kenta-shimizu** [comment]
Hi,
I don't know either. something is off.

Wrong points in diagram:
- Session-ID of Reply-Messsage is wrong. NOT equals Session-ID of Primary-Message.
- NOT send S1F15. Send Separate-req.
- HSMS-GS Example is 6.

Difference is:
'ActiveOne' is open 1 session [100].
'ActiveTwo' is open 2 session [200,300] at once.

**Comment by btbtbtbjjzz** [comment]
Thanks so much!I have another question,what is the difference between HSMS-SS and HSMS-GS
？

**Comment by kenta-shimizu** [comment]
HSMS-SS is defined in SEMI-E37.1.
'-SS' is Single Session.
'-SS' is simple set of HSMS(SEMI-E37). Replacement from SECS-I(E4)
'-SS' is good enough for use.

HSMS-GS is defined in SEMI-E37.2.
'-GS' is General Session.
'-GS' is full set of HSMS(SEMI-E37)
'-GS' is unnecessarily complicated.

If you choose, recommend HSMS-SS.
I have never seen any equipment that uses HSMS-GS.

**Comment by btbtbtbjjzz** [comment]
I see, thank you very much for your help.
