### ISSUE TITLE
how to support hsms mutiple session?

### ISSUE THREAD

**Issue by shyding** [kenta-shimizu/secs4java8#5]
now only support hsms single session? but how to support hsms mutiple session?

**Comment by shyding** [comment]
it means how to support HSMS-GS？

**Comment by kenta-shimizu** [comment]
I can't answer how to do because I don't know HSMS-GS.
I want anyone to teach me.

**Comment by kenta-shimizu** [comment]
Today, I read HSMS-GS standard.
I git branch "to4.0" and make directory "hsmsgs".

**Comment by shyding** [comment]
the standard is e37.2

**Comment by shyding** [comment]
Mutiple HSMS connection :
1, A host may connect to serveal units of equpiment.
2 , a equipment may be connected by serveal hosts

**Comment by kenta-shimizu** [comment]
Pre-release, HSMS-GS support.

**Comment by shyding** [comment]
thank you for your HSMS-GS support . But one case the current HSMS-GS can't support. The case  is  that the passive side does't know which active side will connect, so that the passive side does't know all sessionIds . But the current HSMS-GS must know all sessionIds before open socket.

**Comment by kenta-shimizu** [comment]
Hi,
If use HSMS, User must know all TCP/IP-address and SESSION-ID perfectly.
If SESSION-ID not registered, SELECT.RSP status is 0x4.
