### ISSUE TITLE
SecsMessageReceiveListener  does not work

### ISSUE THREAD

**Issue by skay0424** [kenta-shimizu/secs4java8#6]
only SecsLogListener can receive meesage ,SecsMessageReceiveListener   does not work !
can you tell me the principle?

**Comment by kenta-shimizu** [comment]
'SecsLogListener' and 'SecsMessageReceiveListener' have nothing to do with each other.

'SecsCommunicator#addSecsMessageReceiveListener' receive only Primary-message, not receive Reply-message.
'SecsCommunicator#send' return Optional&lt;SecsMessage&gt;, Optional has value if Reply-message exist.

If you receive both message, use 'SecsCommunicator#addReceiveMessagePassThroughListener'.

**Comment by skay0424** [comment]
> 'SecsLogListener' and 'SecsMessageReceiveListener' have nothing to do with each other.
> 
> 'SecsCommunicator#addSecsMessageReceiveListener' receive only Primary-message, not receive Reply-message. 'SecsCommunicator#send' return Optional<SecsMessage>, Optional has value if Reply-message exist.
> 
> If you receive both message, use 'SecsCommunicator#addReceiveMessagePassThroughListener'.

Thanks for you answer very much!
but,I use your  simulator test,The LogListener is aways can receive message,i thought maybe i could just only registry LogListener!
