### ISSUE TITLE
about build Secs2 Message quesion 

### ISSUE THREAD

**Issue by skay0424** [kenta-shimizu/secs4java8#7]
eg : Secs2.list(
                    Secs2.uint2(portListRptId), //DATAID
                    Secs2.uint4(eventId),
                    Secs2.list(    //L:a
                            Secs2.list(  //L:2
                                    Secs2.uint4(portListRptId), //rptId
                                    Secs2.list(  //L:b
                                            /*
                                                V
                                             */
                                            Secs2.ascii(agvCode), // agvCode
                                            Secs2.list(
                                                    Secs2.ascii(ports.get(0)), //port1
                                                    Secs2.ascii(ports.get(1)) // port2
                                            )
                                    )
                            )
                    )

            );

the params port1 and port2  is List, it maybe one or more ,how do i build him, does it support foreach

**Comment by kenta-shimizu** [comment]
Hi,
interface Secs2 has
static #list(List&lt;? extends Secs2&gt; values);
 
/* build Port List from String to Secs2 example */                                    
List&lt;String&gt; ports = Arrays.asList("P1", "P2");
List&lt;Secs2&gt; ss = ports.stream().map(Secs2::ascii).collect(Collectors.toList());
Secs2 portList = Secs2.list(ss);

**Comment by skay0424** [comment]
> Hi, interface Secs2 has static #list(List<? extends Secs2> values);
> 
> /* build Port List from String to Secs2 example */ List<String> ports = Arrays.asList("P1", "P2"); List<Secs2> ss = ports.stream().map(Secs2::ascii).collect(Collectors.toList()); Secs2 portList = Secs2.list(ss);

Thanks very much
