### ISSUE TITLE
SecsCommunicatableStateChangeListener What state does it listener

### ISSUE THREAD

**Issue by skay0424** [kenta-shimizu/secs4java8#9]
Hi,we are passive,SecsCommunicatableStateChangeListener listener state is false,In this state, we send a message, the other party can't receive it, the other party sends a message, we can receive it! Our system will receive HsmsNotConnectionException!
please tell me why? thanks

**Comment by kenta-shimizu** [comment]
Hi,

In HSMS-SS-Communicator, listener notify true if HSMS-State changed to SELECTED, otherwise false.

If state is not SELECTED, HSMS-SS-Communicator#send throw Exception.

To send Data-Message in passive, wait until state changed to SELECTED.

Thanks regards.

**Comment by skay0424** [comment]
Thank you very much.
 I got some news today
The other side is deploying two servers in the same system and connecting to my semi at the same time. One machine is down, and they hope we can send it to the other, but HSMS State is false, and we can't send messages. Is this solution feasible?

**Comment by kenta-shimizu** [comment]
HSMS-SS is Single Session.
Two servers cannot be connected at the same time.
